"use server";

import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function updateHubPdl(formData: FormData) {
  const session = await requireSession();
  if (!session.isAdmin) throw new Error("Nur für Admins.");

  const hubId = String(formData.get("hub_id") ?? "");
  const pdlName = String(formData.get("pdl_name") ?? "").trim();
  const pdlEmail = String(formData.get("pdl_email") ?? "").trim();
  const pdlPhone = String(formData.get("pdl_phone") ?? "").trim();
  const address = String(formData.get("address") ?? "").trim();
  const ikNummer = String(formData.get("ik_nummer") ?? "").trim();
  const mdEmail = String(formData.get("md_email") ?? "").trim();
  if (!hubId) return;

  const patch = {
    pdl_name: pdlName || null,
    pdl_email: pdlEmail || null,
    pdl_phone: pdlPhone || null,
    address: address || null,
  };
  const supabase = await createClient();
  const { error } = await supabase
    .from("hubs")
    .update({ ...patch, ik_nummer: ikNummer || null, md_email: mdEmail || null })
    .eq("id", hubId);
  // Spalten ik_nummer/md_email existieren erst nach Migration 0025/0028 —
  // bis dahin die übrigen Felder trotzdem speichern.
  if (error && (error.code === "PGRST204" || error.code === "42703")) {
    await supabase.from("hubs").update(patch).eq("id", hubId);
  }

  revalidatePath("/admin");
  revalidatePath("/hubs");
  revalidatePath("/hubs/[id]", "page");
}

type Result = { ok: true } | { ok: false; error: string };

/** Create a new hub. share_token is generated by the DB default. */
export async function createHub(input: {
  name: string;
  region?: string;
  address?: string;
  responsible_md?: string;
}): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };

  const name = (input.name ?? "").trim();
  if (!name) return { ok: false, error: "Name eingeben." };

  const supabase = await createClient();
  const { error } = await supabase.from("hubs").insert({
    name,
    region: (input.region ?? "").trim() || null,
    address: (input.address ?? "").trim() || null,
    responsible_md: (input.responsible_md ?? "").trim() || null,
  });
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  revalidatePath("/");
  revalidatePath("/hubs");
  return { ok: true };
}

/**
 * Delete a hub including all seiner Daten. Einträge (activities) und
 * Lieferungen referenzieren hubs mit ON DELETE RESTRICT — sie werden vorab
 * explizit gelöscht; alles andere (Placements, Patienten-Listen/-Meldungen,
 * user_hubs, Task-Häkchen) cascadet, Bestellungen behalten via SET NULL
 * ihren Text. Admin-only; die UI verlangt eine Bestätigung.
 */
export async function deleteHub(id: string): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };
  if (!id) return { ok: false, error: "Hub fehlt." };

  const admin = createAdminClient();

  // Restrict-FKs zuerst: Einträge und Lieferungen des Hubs entfernen.
  const { error: actErr } = await admin
    .from("activities")
    .delete()
    .eq("hub_id", id);
  if (actErr) {
    return { ok: false, error: "Einträge des Hubs konnten nicht gelöscht werden." };
  }
  const { error: delErr } = await admin
    .from("deliveries")
    .delete()
    .eq("hub_id", id);
  if (delErr) {
    return { ok: false, error: "Lieferungen des Hubs konnten nicht gelöscht werden." };
  }

  const { error } = await admin.from("hubs").delete().eq("id", id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  revalidatePath("/hubs");
  revalidatePath("/");
  return { ok: true };
}

/**
 * Neuen Katalog-Artikel für den PDL-Shop anlegen. `material_catalog` hat RLS
 * disabled — Zugriff ausschließlich über den Service-Role-Client.
 */
export async function createCatalogItem(input: {
  key: string;
  name: string;
  description?: string;
}): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };

  const key = (input.key ?? "").trim().toLowerCase();
  const name = (input.name ?? "").trim();
  const description = (input.description ?? "").trim();

  if (!key) return { ok: false, error: "Key eingeben." };
  if (!/^[a-z0-9_-]+$/.test(key)) {
    return {
      ok: false,
      error: "Key darf nur Kleinbuchstaben, Zahlen, - und _ enthalten.",
    };
  }
  if (!name) return { ok: false, error: "Name eingeben." };

  const admin = createAdminClient();

  // Neue Artikel ans Ende sortieren.
  const { data: last } = await admin
    .from("material_catalog")
    .select("sort_order")
    .order("sort_order", { ascending: false })
    .limit(1);
  const nextSort = (last?.[0]?.sort_order ?? 0) + 1;

  const { error } = await admin.from("material_catalog").insert({
    key,
    name,
    description: description || null,
    category: "material",
    sort_order: nextSort,
  });
  if (error) {
    if (error.code === "23505") {
      return { ok: false, error: `Key „${key}“ existiert bereits.` };
    }
    return { ok: false, error: error.message };
  }

  revalidatePath("/admin");
  return { ok: true };
}

/** Katalog-Artikel aktiv/inaktiv schalten (inaktiv = im Shop ausgeblendet). */
export async function setCatalogItemActive(
  id: string,
  active: boolean,
): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };
  if (!id) return { ok: false, error: "Artikel fehlt." };

  const admin = createAdminClient();
  const { error } = await admin
    .from("material_catalog")
    .update({ active })
    .eq("id", id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  return { ok: true };
}

/** Wochen-Mails manuell auslösen (Test/Nachholen) — nutzt dieselbe Logik wie der Montags-Cron. */
export async function triggerWeeklyMails(
  kind: "md" | "pdl",
): Promise<{ ok: boolean; message: string }> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, message: "Nur für Admins." };

  const { mailConfigured } = await import("@/lib/mailer");
  if (!mailConfigured()) {
    return {
      ok: false,
      message:
        "Kein Mail-Versandweg eingerichtet — Outlook verbinden oder SMTP-Zugangsdaten (Gmail-App-Passwort) setzen.",
    };
  }

  const { sendMdUpdates, sendPdlReminders } = await import(
    "@/lib/weekly-mails"
  );
  const r = kind === "md" ? await sendMdUpdates() : await sendPdlReminders();
  const parts = [
    r.sent.length > 0 ? `Gesendet: ${r.sent.join("; ")}` : "Nichts gesendet.",
    r.skipped.length > 0 ? `Übersprungen: ${r.skipped.join("; ")}` : "",
    r.errors.length > 0 ? `Fehler: ${r.errors.join("; ")}` : "",
  ].filter(Boolean);
  return { ok: r.errors.length === 0, message: parts.join(" · ") };
}

/**
 * Freie Update-Mail aus dem Admin an gewählte Empfänger:
 * PDLs (je Standort), MDs (hinterlegte md_email) und zusätzliche Adressen
 * (z. B. Geschäftsführung). Jeder Empfänger bekommt eine eigene Mail —
 * keine sichtbare Empfängerliste.
 */
export async function sendAdminMail(input: {
  subject?: string;
  body?: string;
  pdlHubIds?: string[];
  includeMds?: boolean;
  extra?: string;
}): Promise<{ ok: boolean; message: string }> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, message: "Nur für Admins." };

  const subject = (input.subject ?? "").trim().slice(0, 200);
  const bodyText = (input.body ?? "").trim().slice(0, 8000);
  if (!subject) return { ok: false, message: "Betreff angeben." };
  if (!bodyText) return { ok: false, message: "Nachricht angeben." };

  const { mailConfigured, deliverMail } = await import("@/lib/mailer");
  if (!mailConfigured()) {
    return {
      ok: false,
      message:
        "Kein Mail-Versandweg eingerichtet — SMTP-Zugangsdaten setzen oder Outlook verbinden.",
    };
  }

  const { splitPdlEmails } = await import("@/lib/pdl");
  const admin = createAdminClient();
  const { data: hubRows } = await admin.from("hubs").select("*");
  const hubs = (hubRows ?? []) as import("@/lib/types").Hub[];

  // Empfänger einsammeln (dedupliziert, mit Anzeige-Label).
  const recipients = new Map<string, string>();
  const pdlHubIds = new Set(input.pdlHubIds ?? []);
  for (const h of hubs) {
    if (pdlHubIds.has(h.id)) {
      for (const e of splitPdlEmails(h.pdl_email)) {
        recipients.set(e.toLowerCase(), `${h.name} (PDL)`);
      }
    }
  }
  if (input.includeMds) {
    for (const h of hubs) {
      const e = (h.md_email ?? "").trim().toLowerCase();
      if (e.includes("@") && !recipients.has(e)) {
        recipients.set(e, `${h.responsible_md ?? "MD"} (MD)`);
      }
    }
  }
  for (const raw of (input.extra ?? "").split(/[,;\s]+/)) {
    const e = raw.trim().toLowerCase();
    if (e.includes("@")) recipients.set(e, "Weitere");
  }
  if (recipients.size === 0) {
    return { ok: false, message: "Keine Empfänger ausgewählt/gefunden." };
  }
  if (recipients.size > 100) {
    return { ok: false, message: "Mehr als 100 Empfänger — bitte eingrenzen." };
  }

  const esc = (s: string) =>
    s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  const html = `<div style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;color:#1f2430;line-height:1.5">
${bodyText
  .split(/\n{2,}/)
  .map((p) => `<p>${esc(p).replace(/\n/g, "<br>")}</p>`)
  .join("\n")}
<p>Viele Grüße<br>Ihr Marketing-Team<br>
Tel. 0177 2988 173 · <a href="mailto:marketing@igs-holding.de">marketing@igs-holding.de</a></p>
</div>`;

  const sent: string[] = [];
  const errors: string[] = [];
  for (const [email, label] of recipients) {
    const res = await deliverMail({ to: [email], subject, html });
    if (res.ok) sent.push(`${label} <${email}>`);
    else errors.push(`${label} <${email}>: ${res.error}`);
  }

  return {
    ok: errors.length === 0,
    message:
      `Gesendet an ${sent.length} Empfänger.` +
      (errors.length > 0 ? ` Fehler: ${errors.join("; ")}` : ""),
  };
}
