"use server";

import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function updateHubPdl(formData: FormData) {
  const session = await requireSession();
  if (!session.isAdmin) throw new Error("Nur für Admins.");

  const hubId = String(formData.get("hub_id") ?? "");
  const pdlName = String(formData.get("pdl_name") ?? "").trim();
  const pdlEmail = String(formData.get("pdl_email") ?? "").trim();
  const pdlPhone = String(formData.get("pdl_phone") ?? "").trim();
  const address = String(formData.get("address") ?? "").trim();
  if (!hubId) return;

  const supabase = await createClient();
  await supabase
    .from("hubs")
    .update({
      pdl_name: pdlName || null,
      pdl_email: pdlEmail || null,
      pdl_phone: pdlPhone || null,
      address: address || null,
    })
    .eq("id", hubId);

  revalidatePath("/admin");
  revalidatePath("/hubs");
}

type Result = { ok: true } | { ok: false; error: string };

/** Create a new hub. share_token is generated by the DB default. */
export async function createHub(input: {
  name: string;
  region?: string;
  address?: string;
  responsible_md?: string;
}): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };

  const name = (input.name ?? "").trim();
  if (!name) return { ok: false, error: "Name eingeben." };

  const supabase = await createClient();
  const { error } = await supabase.from("hubs").insert({
    name,
    region: (input.region ?? "").trim() || null,
    address: (input.address ?? "").trim() || null,
    responsible_md: (input.responsible_md ?? "").trim() || null,
  });
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  revalidatePath("/");
  revalidatePath("/hubs");
  return { ok: true };
}

/**
 * Delete a hub. Deliveries reference hubs with ON DELETE RESTRICT, so a hub that
 * already has recorded deliveries cannot be removed — we surface that clearly
 * instead of a raw FK error. Placements cascade; orders keep their text via
 * ON DELETE SET NULL.
 */
export async function deleteHub(id: string): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };
  if (!id) return { ok: false, error: "Hub fehlt." };

  const supabase = await createClient();

  const { count } = await supabase
    .from("deliveries")
    .select("id", { count: "exact", head: true })
    .eq("hub_id", id);
  if ((count ?? 0) > 0) {
    return {
      ok: false,
      error: `Hub hat ${count} Lieferung(en) und kann nicht gelöscht werden.`,
    };
  }

  const { error } = await supabase.from("hubs").delete().eq("id", id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  revalidatePath("/hubs");
  revalidatePath("/");
  return { ok: true };
}

/**
 * Neuen Katalog-Artikel für den PDL-Shop anlegen. `material_catalog` hat RLS
 * disabled — Zugriff ausschließlich über den Service-Role-Client.
 */
export async function createCatalogItem(input: {
  key: string;
  name: string;
  description?: string;
}): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };

  const key = (input.key ?? "").trim().toLowerCase();
  const name = (input.name ?? "").trim();
  const description = (input.description ?? "").trim();

  if (!key) return { ok: false, error: "Key eingeben." };
  if (!/^[a-z0-9_-]+$/.test(key)) {
    return {
      ok: false,
      error: "Key darf nur Kleinbuchstaben, Zahlen, - und _ enthalten.",
    };
  }
  if (!name) return { ok: false, error: "Name eingeben." };

  const admin = createAdminClient();

  // Neue Artikel ans Ende sortieren.
  const { data: last } = await admin
    .from("material_catalog")
    .select("sort_order")
    .order("sort_order", { ascending: false })
    .limit(1);
  const nextSort = (last?.[0]?.sort_order ?? 0) + 1;

  const { error } = await admin.from("material_catalog").insert({
    key,
    name,
    description: description || null,
    category: "material",
    sort_order: nextSort,
  });
  if (error) {
    if (error.code === "23505") {
      return { ok: false, error: `Key „${key}“ existiert bereits.` };
    }
    return { ok: false, error: error.message };
  }

  revalidatePath("/admin");
  return { ok: true };
}

/** Katalog-Artikel aktiv/inaktiv schalten (inaktiv = im Shop ausgeblendet). */
export async function setCatalogItemActive(
  id: string,
  active: boolean,
): Promise<Result> {
  const session = await requireSession();
  if (!session.isAdmin) return { ok: false, error: "Nur für Admins." };
  if (!id) return { ok: false, error: "Artikel fehlt." };

  const admin = createAdminClient();
  const { error } = await admin
    .from("material_catalog")
    .update({ active })
    .eq("id", id);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/admin");
  return { ok: true };
}
